Script for reproducing issue 2322
smartdevicelink/sdl_atf_test_scripts pull request #1957
Opened 2018-07-03 14:08 UTC by HSavynetska

Script for reproducing issue [SDL must set media app to LIMITED and AUDIBLE due to active embedded navigation](https://github.com/smartdevicelink/sdl_core/issues/2322)

2018-07-25 12:54 UTC, GetmanetsIrina commented on test_scripts/Defects/4_6/2322_SDL_must_set_media_app_to_LIMITED_and_AUDIBLE_due_to_active_embedded_navigation.lua
> +config.application1 = {
There is no need to redefine all params for application1.
It is enough to redefine:
```
config.application1.registerAppInterfaceParams.isMediaApplication = true
config.application1.registerAppInterfaceParams.appHMIType = { "MEDIA" }
```

2018-07-25 12:55 UTC, GetmanetsIrina commented on test_scripts/Defects/4_6/2322_SDL_must_set_media_app_to_LIMITED_and_AUDIBLE_due_to_active_embedded_navigation.lua
> +local function rai_n(self)
Can be used function `registerApp` from actions.lua instead off local created

2018-07-25 12:56 UTC, GetmanetsIrina commented on test_scripts/Defects/4_6/2322_SDL_must_set_media_app_to_LIMITED_and_AUDIBLE_due_to_active_embedded_navigation.lua
> +  local requestId = self.hmiConnection:SendRequest("SDL.ActivateApp", { appID = self.HMIAppID })
appID value can be gotten by using function getHMIAppId(pAppId) from actions.lua

2018-07-25 12:58 UTC, GetmanetsIrina commented on test_scripts/Defects/4_6/2322_SDL_must_set_media_app_to_LIMITED_and_AUDIBLE_due_to_active_embedded_navigation.lua
> +runner.Step("Activate App", activate_app)
Update case name according to actions in case

2020-09-02 20:44 UTC, jacobkeeler requested changes

2020-09-02 20:44 UTC, jacobkeeler commented on test_scripts/Defects/5_0/2322_SDL_must_set_media_app_to_LIMITED_and_AUDIBLE_due_to_active_embedded_navigation.lua
> +	{ hmiLevel = "LIMITED", audioStreamingState = "NOT_AUDIBLE", systemContext = "MAIN" })
```suggestion
	{ hmiLevel = "LIMITED", audioStreamingState = "AUDIBLE", systemContext = "MAIN" })
```

2020-09-02 20:45 UTC, jacobkeeler commented on test_scripts/Defects/5_0/2322_SDL_must_set_media_app_to_LIMITED_and_AUDIBLE_due_to_active_embedded_navigation.lua
> +-- SDL must send OnHMIStatus(LIMITED, NOT_AUDIBLE) to mobile app.
```suggestion
-- SDL must send OnHMIStatus(LIMITED, AUDIBLE) to mobile app.
```

2020-09-08 21:25 UTC, jacobkeeler commented
Closing in favor of #2452

2020-09-08 21:25 UTC, closed without merging