Script for reproducing issue 1906
smartdevicelink/sdl_atf_test_scripts pull request #1977
Opened 2018-07-17 08:31 UTC by HSavynetska

Script for reproducing issue [Navigation app must be activated during active embedded navigation and "MixingAudioSupported" = true](https://github.com/smartdevicelink/sdl_core/issues/1906)

2020-05-05 14:33 UTC, GetmanetsIrina commented
PR is rebased on current develop(a7db5cc) branch.
Script is applicable for all policy flows and transport types.
Script has been moved to 6_1 folder.
Test set for script is added.

2020-09-02 19:03 UTC, jacobkeeler requested changes

2020-09-02 19:03 UTC, jacobkeeler commented on test_scripts/Defects/6_1/1906_Navigation_app_must_be_activated_during_active_embedded_navigation_and_MixingAudioSupported_true.lua
> +-- 4) Navigation app in LIMITED and NOT_AUDIBLE due to active embedded audio source
```suggestion
-- 4) Navigation app in LIMITED and AUDIBLE due to active embedded audio source
```

2020-09-02 19:03 UTC, jacobkeeler commented on test_scripts/Defects/6_1/1906_Navigation_app_must_be_activated_during_active_embedded_navigation_and_MixingAudioSupported_true.lua
> +    { hmiLevel = "BACKGROUND", audioStreamingState = "NOT_AUDIBLE" })
```suggestion
    { hmiLevel = "LIMITED", audioStreamingState = "AUDIBLE" })
```

2020-09-08 21:25 UTC, jacobkeeler commented
Closing in favor of #2452

2020-09-08 21:25 UTC, closed without merging