Scripts to check issue 1917
smartdevicelink/sdl_atf_test_scripts pull request #2088
Opened 2018-09-28 16:21 UTC by mkorniichuk

ATF Test Scripts to check [#1917](https://github.com/SmartDeviceLink/sdl_core/issues/1917)
This PR is **not ready** for review.
This is **draft** version of the script.

### Summary
A test script to verify that issue is fixed

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2018-10-26 14:47 UTC, dboltovskyi commented
Livio team please do not review this PR for now since it hasn't passed our internal review yet.  
Review and appropriate updates going be done till 1st of November.
Thank you.

2020-05-13 10:46 UTC, GetmanetsIrina commented
PR is rebased on current develop(8b2019d) branch.
Script is applicable for all policy flows and transport types.
Script has been moved to 6_1 folder.
Test set for script is added.

2020-09-02 20:42 UTC, jacobkeeler requested changes

2020-09-02 20:42 UTC, jacobkeeler commented on test_scripts/Defects/6_1/1917_Media_navigation_and_nonmedia_apps_must_be_activated_during_active_embedded_audio_source.lua
> +      config["application"..pAppId].registerAppInterfaceParams.appHMIType[1] == "NAVIGATION"
```suggestion
      config["application"..pAppId].registerAppInterfaceParams.appHMIType[1] == "NAVIGATION"
```
`NAVIGATION` app is `STREAMABLE` from `LIMITED`

2020-09-02 20:42 UTC, jacobkeeler commented on test_scripts/Defects/6_1/1917_Media_navigation_and_nonmedia_apps_must_be_activated_during_active_embedded_audio_source.lua
> +    { hmiLevel = "BACKGROUND", audioStreamingState = "NOT_AUDIBLE", videoStreamingState = "NOT_STREAMABLE" })
```suggestion
  -- hmiLevel = "LIMITED", audioStreamingState = "AUDIBLE", videoStreamingState = "STREAMABLE"
  common.getMobileSession(2):ExpectNotification("OnHMIStatus"):Times(0)
```
App would be in `LIMITED`, `AUDIBLE`, `STREAMABLE`

2020-09-02 20:42 UTC, jacobkeeler commented on test_scripts/Defects/6_1/1917_Media_navigation_and_nonmedia_apps_must_be_activated_during_active_embedded_audio_source.lua
> +    { hmiLevel = "LIMITED", audioStreamingState = "AUDIBLE" })
```suggestion
  -- hmiLevel = "LIMITED", audioStreamingState = "AUDIBLE", videoStreamingState = "STREAMABLE"
  common.getMobileSession(2):ExpectNotification("OnHMIStatus"):Times(0)
```
App would be in `LIMITED`, `AUDIBLE`, `STREAMABLE`

2020-09-08 21:24 UTC, jacobkeeler commented
Closing in favor of #2452

2020-09-08 21:24 UTC, closed without merging