Script for defect 1918
smartdevicelink/sdl_atf_test_scripts pull request #2089
Opened 2018-09-28 16:26 UTC by mkorniichuk

ATF Test Scripts to check [#1918](https://github.com/SmartDeviceLink/sdl_core/issues/1918)

This PR is **not ready** for review.

### Summary
A test script to verify that issue is fixed

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2018-10-26 14:47 UTC, dboltovskyi commented
Livio team please do not review this PR for now since it hasn't passed our internal review yet.  
Review and appropriate updates going be done till 1st of November.
Thank you.

2020-05-15 11:08 UTC, GetmanetsIrina commented
PR is rebased on current develop(a2040db) branch.
Script is applicable for all policy flows and transport types.
Script has been moved to 6_1 folder.
Test set for script is added.

2020-09-02 20:49 UTC, jacobkeeler requested changes

2020-09-02 20:49 UTC, jacobkeeler commented on test_scripts/Defects/6_1/1918_Multiple_apps_activation_during_active_embedded_audio_source.lua
> +      then
`NAVIGATION` app would be `STREAMABLE`

2020-09-02 20:57 UTC, jacobkeeler requested changes

2020-09-02 20:57 UTC, jacobkeeler commented on test_scripts/Defects/6_1/1918_Multiple_apps_activation_during_active_embedded_audio_source.lua
> +  })
```suggestion
  -- hmiLevel = "LIMITED", audioStreamingState = "AUDIBLE", videoStreamingState = "STREAMABLE"
  common.getMobileSession(2):ExpectNotification("OnHMIStatus"):Times(0)
```
App would be in `LIMITED`, `AUDIBLE`, `STREAMABLE`

2020-09-02 20:57 UTC, jacobkeeler commented on test_scripts/Defects/6_1/1918_Multiple_apps_activation_during_active_embedded_audio_source.lua
> +local function embededAudioActivated()
```suggestion
local function embeddedAudioActivated()
```

2020-09-02 20:57 UTC, jacobkeeler commented on test_scripts/Defects/6_1/1918_Multiple_apps_activation_during_active_embedded_audio_source.lua
> +    { hmiLevel = "LIMITED", audioStreamingState = "AUDIBLE" })
```suggestion
  -- hmiLevel = "LIMITED", audioStreamingState = "AUDIBLE", videoStreamingState = "STREAMABLE"
  common.getMobileSession(2):ExpectNotification("OnHMIStatus"):Times(0)
```
App would be in `LIMITED`, `AUDIBLE`, `STREAMABLE`

2020-09-08 21:24 UTC, jacobkeeler commented
Closing in favor of #2452

2020-09-08 21:24 UTC, closed without merging