update 090 to new common files
smartdevicelink/sdl_atf_test_scripts pull request #2479
Opened 2020-11-16 17:22 UTC by iCollin

This PR is **ready** for review.

### Summary
this test was a non-actual failure. i've updated it to use the new common files so this test will be valid.

### ATF version
latest

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2020-11-18 15:49 UTC, jacobkeeler requested changes

2020-11-18 15:49 UTC, jacobkeeler commented on test_scripts/Policies/build_options/090_ATF_For_PTU_use_consented_device_only.lua
> +local common2 = require('test_scripts/Capabilities/PersistingHMICapabilities/common')
```suggestion

--[[ Test Configuration ]]
runner.testSettings.isSelfIncluded = false
```
common2 shouldn't be needed, I think the issue is that `isSelfIncluded = false` is missing.

2020-11-18 15:49 UTC, jacobkeeler commented on test_scripts/Policies/build_options/090_ATF_For_PTU_use_consented_device_only.lua
> +runner.Step("Start SDL, HMI", common2.start)
```suggestion
runner.Step("Start SDL, HMI", common.start)
```

2020-11-18 15:49 UTC, jacobkeeler commented on test_scripts/Policies/build_options/090_ATF_For_PTU_use_consented_device_only.lua
> +  EXPECT_HMIRESPONSE(RequestId, {result = { code = 0, device = { name = devices[2].name }, isSDLAllowed = false, method = "SDL.ActivateApp" }})
```suggestion
  common.getHMIConnection():ExpectResponse(RequestId, {result = { code = 0, device = { name = devices[2].name }, isSDLAllowed = false, method = "SDL.ActivateApp" }})
```
for consistency

2020-11-18 15:49 UTC, jacobkeeler commented on test_scripts/Policies/build_options/090_ATF_For_PTU_use_consented_device_only.lua
> +    EXPECT_HMIRESPONSE(RequestIdGetMes)
```suggestion
    common.getHMIConnection():ExpectResponse(RequestIdGetMes)
```

2020-11-18 15:49 UTC, jacobkeeler commented on test_scripts/Policies/build_options/090_ATF_For_PTU_use_consented_device_only.lua
> +    EXPECT_HMICALL("BasicCommunication.PolicyUpdate")
```suggestion
    common.getHMIConnection():ExpectRequest("BasicCommunication.PolicyUpdate")
```

2020-11-18 22:25 UTC, iCollin commented
Great catch on `isSelfIncluded`, all comments were adressed in https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2479/commits/669c8680a255840c488d74d164f59b9988e56ccb

2020-11-19 02:03 UTC, dboltovskyi commented
@iCollin Please consider 2 items from my side:
1. In order to support (and restrict) more connection types and SDL configurations I would suggest to make updates similar the ones described in https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2485
2. Add script into policy test set: `policies_happy_paths_EXTERNAL_PROPRIETARY.txt` and enable it in `policies_all_flows.txt`

2020-11-20 14:41 UTC, jacobkeeler approved these changes

2020-11-20 19:16 UTC, merged