[SDL 0238] Scripts for `Keyboard Enhancements` feature
smartdevicelink/sdl_atf_test_scripts pull request #2500
Opened 2020-12-18 13:09 UTC by GetmanetsIrina

ATF Test Scripts to check [#2970](https://github.com/smartdevicelink/sdl_core/issues/2970)

This PR is **[not ready]** for review.

### Summary
New scripts for the `Keyboard Enhancements` feature

### ATF version
[feature/7.1.0_version_bump](https://github.com/smartdevicelink/sdl_atf/tree/feature/7.1.0_version_bump)

### Changelog
 - Added new scripts for the feature
 - Added new test set for the feature

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-01-06 13:27 UTC, KhrystynaDubovyk commented
@ashwink11, please review this PR.

2021-01-07 11:55 UTC, ashwink11 commented
@KhrystynaDubovyk changes approved from the Ford side.

2021-01-08 14:37 UTC, KhrystynaDubovyk commented
@JackLivio This PR is ready for Livio ready. Thank you!

2021-01-08 16:03 UTC, ashwink11 commented
@jordynmackool  this PR is ready for review. Thanks!

2021-01-25 21:57 UTC, jacobkeeler requested changes

2021-01-25 21:57 UTC, jacobkeeler commented on test_scripts/API/KeyboardEnhancements/SetGlobalProperties/006_App_defines_invalid_value_in_customizeKeys.lua
> +  configurableKeys = { { keyboardLayout = "NUMERIC", numConfigurableKeys = 11 } }
```suggestion
  configurableKeys = { { keyboardLayout = "NUMERIC", numConfigurableKeys = 10 } }
```

2021-01-25 21:57 UTC, jacobkeeler commented on test_scripts/API/KeyboardEnhancements/SetGlobalProperties/008_App_defines_not_supported_special_character_in_customizeKeys.lua
> +      customizeKeys = { "^" } -- not supported special character
```suggestion
      customizeKeys = { "^" } -- special character that is not supported by HMI
```

2021-01-26 10:45 UTC, GetmanetsIrina commented on test_scripts/API/KeyboardEnhancements/Capabilities/001_HMI_provides_valid_values_for_all_parameters_in_KeyboardCapabilities.lua
> +common.Step("HMI sends OnSCU", common.sendOnSCU)
@jacobkeeler, fixed in 0239770 .

2021-01-26 10:45 UTC, GetmanetsIrina commented on test_scripts/API/KeyboardEnhancements/SetGlobalProperties/005_App_defines_customizeKeys_edge_cases.lua
> +  configurableKeys = { { keyboardLayout = "NUMERIC", numConfigurableKeys = 11 } }
@jacobkeeler, fixed in 0239770

2021-01-26 10:45 UTC, GetmanetsIrina commented on test_scripts/API/KeyboardEnhancements/SetGlobalProperties/006_App_defines_invalid_value_in_customizeKeys.lua
> +  configurableKeys = { { keyboardLayout = "NUMERIC", numConfigurableKeys = 11 } }
@jacobkeeler, fixed in 0239770

2021-01-26 10:45 UTC, GetmanetsIrina commented on test_scripts/API/KeyboardEnhancements/SetGlobalProperties/008_App_defines_not_supported_special_character_in_customizeKeys.lua
> +      customizeKeys = { "^" } -- not supported special character
@jacobkeeler, updated in 0239770

2021-01-26 11:01 UTC, GetmanetsIrina commented on test_scripts/API/KeyboardEnhancements/common.lua
> +do
This `do` block was only for more convenient code reading (the variable list minimizing in a text editor). It has been removed in 0239770

2021-01-26 11:03 UTC, GetmanetsIrina commented on test_scripts/API/KeyboardEnhancements/Capabilities/006_SDL_populates_numConfigurableKeys_with_zeros.lua
> +----------------------------------------------------------------------------------------------------
The script will be removed after smartdevicelink/sdl_evolution#1117 is accepted.

2021-01-26 11:04 UTC, GetmanetsIrina commented
@jacobkeeler, all comments are addressed.

2021-01-26 13:33 UTC, GetmanetsIrina commented
d2ad6d0 fixes a typo in the function name.

2021-02-08 19:45 UTC, dboltovskyi commented
@jacobkeeler Please notice all updates related to revision are done and PR is ready for review. Thank you!

2021-02-09 18:17 UTC, jacobkeeler requested changes

2021-02-09 21:09 UTC, dboltovskyi commented on test_scripts/API/KeyboardEnhancements/common.lua
> +  m.tableToString = utils.tableToString
Done in 6aa7b8b

2021-02-10 14:09 UTC, jacobkeeler approved these changes

2021-02-12 14:14 UTC, merged