Add script(s) for issue 1393
smartdevicelink/sdl_atf_test_scripts pull request #2605
Opened 2021-10-28 15:30 UTC by dboltovskyi

ATF Test Scripts to check [#1393](https://github.com/smartdevicelink/sdl_core/issues/1393)

This PR is **[ready]** for review.

### Summary
New ATF scripts to check the issue.

### ATF version
develop

### Changelog
New scripts

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2022-01-26 08:36 UTC, GetmanetsIrina commented
@theresalech this PR is ready for Livio review

2022-02-03 21:34 UTC, jacobkeeler requested changes

2022-02-03 21:34 UTC, jacobkeeler commented on test_scripts/Defects/5_1/1393_ListFiles_from_enumerating_through_the_file_system.lua
> +  common.getMobileSession():ExpectResponse(cid, { success = true, resultCode = "SUCCESS" })
This doesn't cover the original issue. The issue was that if the OS decided to delete a file in the background, the file would still appear in ListFiles. This should be replaced with an OS call to remove the file.

2022-02-04 15:06 UTC, VjKlepikov commented
@jacobkeeler Please find an update in [85df65a](https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2605/commits/85df65a6e854e66e7c99d25ab454b6bc0eacb2dc)

2022-02-04 15:29 UTC, jacobkeeler requested changes

2022-02-04 16:00 UTC, VjKlepikov commented
@jacobkeeler Done in [d6fb14a5](https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2605/commits/d6fb14a51c2438bcfdf84f64cf83716a06ef3c70)

2022-02-04 19:28 UTC, jacobkeeler approved these changes

2022-02-04 19:29 UTC, merged