Test scripts for issue 2655
smartdevicelink/sdl_atf_test_scripts pull request #2656
Opened 2022-04-06 12:05 UTC by VjKlepikov

ATF Test Scripts to check [#2655](https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2655)

This PR is **[ready]** for review.

### Summary
Improve stability GetVehicleData request for 'heading' value as part of gps parameter in scripts:
./test_scripts/API/VehicleData/GetVehicleData/001_GetVD_Success_flow.lua
Update rounding value to the smallest float number

### ATF version
latest

### Changelog
rounded value to the smallest float

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2022-04-06 12:06 UTC, VjKlepikov commented
@theresalech, this PR is ready for Livio review.

2022-04-06 18:36 UTC, jacobkeeler requested changes

2022-04-06 18:36 UTC, jacobkeeler commented on user_modules/api/APITestDataGenerator.lua
> +    end
Any reason we don't just clamp the value? Seems like a more general solution
```suggestion
    value = tonumber(string.format('%.02f', math.min(math.max(random, min), max)))
```

2022-04-07 12:02 UTC, VjKlepikov commented
@jacobkeeler Please find an update [321b41](https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2656/commits/321b4122224adb2f4b93eceaf92b83027923a705)

2022-04-21 18:05 UTC, merged