Add script to verify issue 2716
smartdevicelink/sdl_atf_test_scripts pull request #2666
Opened 2022-04-22 12:38 UTC by GetmanetsIrina

ATF Test Scripts to check #[2716](https://github.com/smartdevicelink/sdl_core/issues/2716)

This PR is **ready** for review.

### Summary
Added new script to check `OnSystemRequest("requestType" = "OEM_SPECIFIC")` with binary data

### ATF version
develop

### Changelog
- New script added
- Test set is updated with new script

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2022-04-27 13:35 UTC, GetmanetsIrina commented
@theresalech, this PR is ready for Livio review.

2022-06-01 20:20 UTC, ShobhitAd requested changes

2022-06-01 20:20 UTC, ShobhitAd commented on test_scripts/API/Expanded_proprietary_data_exchange/018_OnSystemRequest_with_OEM_SPECIFIC_requestType_binaryData.lua
> +local content = "ABC"
Might want to use something like a key-value pair for the binaryData content (as mentioned in the original issue)
```suggestion
local content = "{\"key\":\"value\"}"
```
or test with multiple content values

2022-06-03 08:35 UTC, GetmanetsIrina commented
@ShobhitAd, pleaase find updates in [1047010](https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2666/commits/10470102a1977bed20522b9ad375331f4af8c10c).

2022-06-03 15:19 UTC, ShobhitAd approved these changes

2022-06-03 15:20 UTC, merged