Add test scripts for issue 2467
smartdevicelink/sdl_atf_test_scripts pull request #2667
Opened 2022-04-26 11:58 UTC by VjKlepikov

ATF Test Scripts to check [#2467](https://github.com/smartdevicelink/sdl_core/issues/2467)

This PR is **[ready]** for review.

### Summary
Add test scripts for issue 2467

### ATF version
latest

### Changelog
Added new script
Test set updated with new added script

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2022-04-26 11:59 UTC, VjKlepikov commented
@theresalech, this PR is ready for Livio review.

2022-06-01 14:12 UTC, ShobhitAd requested changes

2022-06-01 14:12 UTC, ShobhitAd commented on test_scripts/Defects/5_0/2467_Policy_table_corupted_after_first_ign_cycle.lua
> +  common.getHMIConnection():ExpectRequest("Navigation.SendLocation")
```suggestion
  common.getHMIConnection():ExpectRequest("Navigation.SendLocation", { longitudeDegrees = 1.1, latitudeDegrees = 1.1 })
```

2022-06-03 14:07 UTC, VjKlepikov commented
@ShobhitAd Please find the update in [ea32f06](https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2667/commits/ea32f0685df8c98a6f73a604b86c330f31252290)

2022-06-03 15:20 UTC, ShobhitAd approved these changes

2022-06-03 15:21 UTC, merged