Add scripts to verify defect 3888
smartdevicelink/sdl_atf_test_scripts pull request #2675
Opened 2022-05-12 13:09 UTC by GetmanetsIrina

ATF Test Scripts to check #[3888](https://github.com/smartdevicelink/sdl_core/issues/3888)

This PR is **ready** for review.

### Summary
Scripts to check resumption of `CreateInteractionChoiceSet` with and without `VR` command

### ATF version
develop

### Changelog
1. New scripts are added
2. Created scripts are added to the 8_2 test set

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2022-05-12 13:10 UTC, GetmanetsIrina commented
@theresalech, this PR is ready for Livio review.

2022-07-20 18:32 UTC, ShobhitAd requested changes
Please pull in changes from the latest develop and resolve merge conflicts

2022-07-20 18:32 UTC, ShobhitAd commented on test_scripts/Defects/8_2/3888/3888_2_CreateInteractionChoiceSet_resumption_ignition_off.lua
> +-- Description: Check that SDL resumes CreatedInteractionChoice set with and without VR command after ignition off
```suggestion
-- Description: Check that SDL resumes CreatedInteractionChoiceSet with and without VR command after ignition off
```

2022-07-20 18:32 UTC, ShobhitAd commented on test_scripts/Defects/8_2/3888/3888_3_CreateInteractionChoiceSet_resumption_two_sets_unexpected_disc.lua
> +-- Description: Check that SDL resumes both CreatedInteractionChoice sets with and without VR command
```suggestion
-- Description: Check that SDL resumes both CreatedInteractionChoiceSets (one with and one without VR commands)
```

2022-07-20 18:32 UTC, ShobhitAd commented on test_scripts/Defects/8_2/3888/3888_4_CreateInteractionChoiceSet_resumption_two_sets_ignition_off.lua
> +-- Description: Check that SDL resumes both CreatedInteractionChoice sets with and without VR command after ignition off
```suggestion
-- Description: Check that SDL resumes both CreatedInteractionChoiceSets (one with and one without VR commands) after ignition off
```

2022-07-20 18:32 UTC, ShobhitAd commented on test_scripts/Defects/8_2/3888/common.lua
> +local function getPIreqParams()
```suggestion
local function getPIReqParams()
```
Since all the other functions use camelCase might be good to keep it consistent

2022-07-20 18:32 UTC, ShobhitAd commented on test_scripts/Defects/8_2/3888/common.lua
> +function m.additionalResumptionContions(pTimes, pCmdId)
```suggestion
function m.additionalResumptionConditions(pTimes, pCmdId)
```

2022-07-21 14:02 UTC, GetmanetsIrina commented
@ShobhitAd, Luxoft team is not longer support this project.

2022-07-26 13:45 UTC, ShobhitAd commented
Closed in favor of https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2697

2022-07-26 13:45 UTC, closed without merging