Add test scripts for issue 1006
smartdevicelink/sdl_atf_test_scripts pull request #2681
Opened 2022-05-27 09:48 UTC by VjKlepikov

ATF Test Scripts to check [#1006](https://github.com/smartdevicelink/sdl_core/issues/1006)

This PR is **[ready]** for review.

### Summary
Add test scripts for issue 1006

### ATF version
latest

### Changelog
New scripts are added
Test set is updated with new scripts

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2022-05-27 09:50 UTC, VjKlepikov commented
@theresalech, this PR is ready for Livio review.

2022-06-14 17:57 UTC, ShobhitAd requested changes

2022-06-14 17:57 UTC, ShobhitAd commented on test_scripts/Defects/5_0/1006/common.lua
> +    pParams.expectExtraRequest(pParams)
```suggestion
    pParams.expectExtraRequest()
```
All tests with extra requests use `expectExtraRequest = function()` so the passed in `pParams` are never used

2022-06-15 10:11 UTC, VjKlepikov commented
@ShobhitAd please find updates in [0f0486](https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2681/commits/0f0486b6f690606d90bb4a558d5b58daa3e0b314)

2022-06-22 21:22 UTC, merged